const ProjectData = [
  {
    id: "1",
    name: "Depression Recogniser",
    BgColor: "#FDD180",
    cardImg: require("../../Assets/1.svg").default,
    projectLink: "https://covid19-awareness.netlify.app/",
    gitLink: "https://github.com/adarshajit/Depression-Recognizer-for-Twitter",
    features: [
      "Read from a collection of 2000 quotes",
      "Share quote to social media (Currently supports twitter only)",
      "Minimal UI",
      "Fully Responsive",
    ],
    builtWith: [
      "React",
      "Styled Components for styling",
      "react-router-dom: for routing",
      "react-share: social icons",
      "Netlify: for hosting",
    ],
  },

  {
    id: "2",
    name: "Covid-19 Awareness",
    BgColor: "#8D9FFF",
    cardImg: require("../../Assets/2.svg").default,
    projectLink: "https://covid19-awareness.netlify.app/",
    gitLink: "https://github.com/adarshajit/Covid19-Awareness",
    features: [
      "Read from a collection of 2000 quotes",
      "Share quote to social media (Currently supports twitter only)",
      "Minimal UI",
      "Fully Responsive",
    ],
    builtWith: [
      "React",
      "Styled Components for styling",
      "react-router-dom: for routing",
      "react-share: social icons",
      "Netlify: for hosting",
    ],
  },

  {
    id: "3",
    name: "ICEFOSS 2021",
    BgColor: "#B8F7CA",
    cardImg: require("../../Assets/3.svg").default,
    projectLink: "https://icefoss.fisat.ac.in/",
    gitLink: "https://github.com/adarshajit/ICEFOSS2021",
    features: [
      "Read from a collection of 2000 quotes",
      "Share quote to social media (Currently supports twitter only)",
      "Minimal UI",
      "Fully Responsive",
    ],
    builtWith: ["HTML", "Tailwind CSS", "Javascript", "particles.js"],
  },
  {
    id: "4",
    name: "Quotify",
    BgColor: "#ffa3ea",
    cardImg: require("../../Assets/4.svg").default,
    projectLink: "https://quotify-app.netlify.app/",
    gitLink: "https://github.com/adarshajit/Quote-App",
    features: [
      "Read from a collection of 2000 quotes",
      "Share quote to social media (Currently supports twitter only)",
      "Minimal UI",
      "Fully Responsive",
    ],
    builtWith: [
      "React",
      "Styled Components for styling",
      "react-router-dom: for routing",
      "react-share: social icons",
      "Netlify: for hosting",
    ],
  },
  {
    id: "5",
    name: "Technical Essay Assessor",
    BgColor: "#FB8A80",
    cardImg: require("../../Assets/5.svg").default,
    projectLink: "https://icefoss.fisat.ac.in/",
    gitLink: "https://github.com/adarshajit/ICEFOSS2021",
    features: [
      "Read from a collection of 2000 quotes",
      "Share quote to social media (Currently supports twitter only)",
      "Minimal UI",
      "Fully Responsive",
    ],
    builtWith: [
      "React",
      "Styled Components for styling",
      "react-router-dom: for routing",
      "react-share: social icons",
      "Netlify: for hosting",
    ],
  },

  {
    id: "6",
    name: "CRUD Application",
    BgColor: "#A7FFEB",
    cardImg: require("../../Assets/6.svg").default,
    projectLink: "https://icefoss.fisat.ac.in/",
    gitLink: "https://github.com/adarshajit/CRUD-app",
    features: [
      "Read from a collection of 2000 quotes",
      "Share quote to social media (Currently supports twitter only)",
      "Minimal UI",
      "Fully Responsive",
    ],
    builtWith: [
      "React",
      "Styled Components for styling",
      "react-router-dom: for routing",
      "react-share: social icons",
      "Netlify: for hosting",
    ],
  },
];

export default ProjectData;
