const ProjectData = [
  {
    id: "1",
    name: "Depression Recogniser",
    BgColor: "#FDD180",
    cardImg: require("../../Assets/1.svg").default,
    visibility: "block",
    projectLink: "https://depression-recognizer-for-twitter.vercel.app/",
    gitLink: "https://github.com/adarshajit/Depression-Recognizer-for-Twitter",
    features: [
      "Enter a twitter handle to check depression of user",
      "Enter a tweet to detect depression of user",
      "Fetches upto 20 real time tweets of the user",
      "Trained model has an Accuracy of 86%",
      "Minimal UI",
      "Completely Responsive",
    ],
    builtWith: [
      "Tweepy",
      "Django",
      "textblob",
      "nltk",
      "numpy",
      "pandas",
      "sklearn",
      "Algorithm : Multinomial Naive Bayes",
      "React",
      "Styled Components for styling",
      "react-router-dom: for routing",
      "Vercel: for hosting",
    ],

    screenshots: [
      require("../../Assets/Projects/1/user.png").default,
      require("../../Assets/Projects/1/dashboard_user.png").default,
      require("../../Assets/Projects/1/dashboard_tweet.png").default,
    ],
  },

  {
    id: "2",
    name: "Covid-19 Awareness",
    BgColor: "#8D9FFF",
    cardImg: require("../../Assets/2.svg").default,
    visibility: "none",
    projectLink: "https://covid19-awareness.netlify.app/",
    gitLink: "https://github.com/adarshajit/Covid19-Awareness",
    features: [
      "All the neccesary information about COVID-19",
      "Ease of use",
      "Minimal UI",
      "Fully Responsive",
    ],
    builtWith: [
      "React",
      "Styled Components: for styling",
      "react-router-dom: for routing",
      "Netlify: for hosting",
    ],
    screenshots: [require("../../Assets/Projects/2/landing page.png").default],
  },

  {
    id: "3",
    name: "ICEFOSS 2021",
    BgColor: "#B8F7CA",
    cardImg: require("../../Assets/3.svg").default,
    visibility: "none",
    projectLink: "https://icefoss.fisat.ac.in/",
    gitLink: "https://github.com/adarshajit/ICEFOSS2021",
    features: [
      "The official website for ICEFOSS 2021",
      "Fully Responsive",
      "Get information about various workshops and talks all in one place.",
      "Option to register",
    ],
    builtWith: ["HTML", "Tailwind CSS", "Javascript", "particles.js"],
    screenshots: [
      require("../../Assets/Projects/3/landing page.png").default,
      require("../../Assets/Projects/3/register.png").default,
    ],
  },
  {
    id: "4",
    name: "Quotify",
    BgColor: "#ffa3ea",
    cardImg: require("../../Assets/4.svg").default,
    visibility: "none",
    projectLink: "https://quotify-app.netlify.app/",
    gitLink: "https://github.com/adarshajit/Quote-App",
    features: [
      "Read from a collection of 2000 quotes",
      "Share quote to social media (Currently supports twitter only)",
      "Minimal UI",
      "Fully Responsive",
    ],
    builtWith: [
      "React",
      "Styled Components: for styling",
      "react-router-dom: for routing",
      "react-share: social icons",
      "Netlify: for hosting",
    ],
    screenshots: [
      require("../../Assets/Projects/4/landing page.png").default,
      require("../../Assets/Projects/4/quote.png").default,
    ],
  },
  // {
  //   id: "5",
  //   name: "Technical Essay Assessor",
  //   BgColor: "#FB8A80",
  //   cardImg: require("../../Assets/5.svg").default,
  //   projectLink: "https://icefoss.fisat.ac.in/",
  //   gitLink: "https://github.com/adarshajit/ICEFOSS2021",
  //   features: [
  //     "Read from a collection of 2000 quotes",
  //     "Share quote to social media (Currently supports twitter only)",
  //     "Minimal UI",
  //     "Fully Responsive",
  //   ],
  //   builtWith: [
  //     "React",
  //     "Styled Components: for styling",
  //     "react-router-dom: for routing",
  //     "react-share: social icons",
  //     "Netlify: for hosting",
  //   ],
  // },

  // {
  //   id: "5",
  //   name: "CRUD Application",
  //   BgColor: "#A7FFEB",
  //   cardImg: require("../../Assets/6.svg").default,
  //   projectLink: "https://icefoss.fisat.ac.in/",
  //   gitLink: "https://github.com/adarshajit/CRUD-app",
  //   features: [
  //     "Read from a collection of 2000 quotes",
  //     "Share quote to social media (Currently supports twitter only)",
  //     "Minimal UI",
  //     "Fully Responsive",
  //   ],
  //   builtWith: [
  //     "React",
  //     "Styled Components: for styling",
  //     "react-router-dom: for routing",
  //     "react-share: social icons",
  //     "Netlify: for hosting",
  //   ],
  // },
];

export default ProjectData;
